import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
	return (
		<>
			<Head>
				<title>Next.js 13 Tailwind Stater</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className=" container mx-auto min-h-screen p-20 space-y-12">
				<h1 className="flex items-center justify-center  gap-4 text-center text-4xl font-bold ">
					<Image
						className="logo"
						src="/next.svg"
						alt="Next.js Logo"
						width={180}
						height={37}
						priority
					/>
					Tailwiwnd Starter
				</h1>
				<div className="prose prose-invert prose-a:text-blue-300">
					<p>This starter comes configured with:</p>
					<ul>
						<li>Next.js 12</li>
						<li>Next SEO</li>
						<li>Tailwind CSS</li>
						<li>Tailwind Typography</li>
					</ul>
					<Link href="/about">A page using next-seo</Link>
				</div>
				<div className="prose prose-invert mb-16">
					<h2 className="text-2xl">Some things when you clone this starter:</h2>

					<ul className="list-disc list-inside">
						<li>
							Modify{" "}
							<span className="font-mono bg-gray-700">
								src/styles/globals.css
							</span>{" "}
							to remove styles set{" "}
							<span className="font-mono bg-gray-700">body</span>
						</li>
						<li>
							To ensure your meta tags work correctly (if continuing with
							next-seo):
							<ul className="indent- list-disc list-inside">
								<li>
									Update meta tags in{" "}
									<span className="font-mono bg-gray-700">
										next-seo.config.js
									</span>
								</li>
								<li>
									Update meta tags in either{" "}
									<span className="font-mono bg-gray-700">
										src/components/meta.js
									</span>{" "}
									or{" "}
									<span className="font-mono bg-gray-700">src/ui/meta.js</span>{" "}
									depending on the folder structure you are using.
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<Link
					href="https://github.com/Psypher1/nextjs-13-tailwind-starter"
					className="block text-blue-500 text-center text-xl hover:underline transition duration-300"
				>
					Link to the reposiory
				</Link>
			</main>
		</>
	);
}
